---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

transformers:
  # Set namespace to OpenStack on all namespaced objects without a namespace
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack2
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
      - path: metadata/name
        kind: Namespace
        create: true

components:
  - ../../../../../../lib/nncp

resources:
  - values.yaml

patches:
  - target:
      kind: NodeNetworkConfigurationPolicy
      name: ostest-master-0
    patch: |-
      - op: replace
        path: /metadata/name
        value: ostest-master-0-2
  - target:
      kind: NodeNetworkConfigurationPolicy
      name: ostest-master-1
    patch: |-
      - op: replace
        path: /metadata/name
        value: ostest-master-1-2
  - target:
      kind: NodeNetworkConfigurationPolicy
      name: ostest-master-2
    patch: |-
      - op: replace
        path: /metadata/name
        value: ostest-master-2-2

# replacements:
#   - source:
#       kind: ConfigMap
#       name: network-values2
#       fieldPath: data.internalapi.base_iface
#     targets:
#       - select:
#           kind: NodeNetworkConfigurationPolicy
#         fieldPaths:
#           - spec.desiredState.interfaces.[name=internalapi].vlan.base-iface
#   - source:
#       kind: ConfigMap
#       name: network-values2
#       fieldPath: data.bridgeName
#     targets:
#       - select:
#           kind: NodeNetworkConfigurationPolicy
#         fieldPaths:
#           - spec.desiredState.interfaces.[type=linux-bridge].name