---
apiVersion: v1
kind: ConfigMap

metadata:
  name: edpm-deployment-values
  annotations:
    config.kubernetes.io/local-config: "true"

data:
  nodeset:
    ansible:
      ansibleVars:
        edpm_ovn_encap_tos: "inherit"
