---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../dt/bgp/

resources:
  - networking/nncp/values.yaml
  - service-values.yaml

transformers:
  # Set namespace to OpenStack on all namespaced objects without a namespace
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
      - path: metadata/name
        kind: Namespace
        create: true

patches:
  # with BGP, ovnController has to be disabled from OCP nodes
  - target:
      kind: OpenStackControlPlane
      name: controlplane
    patch: |-
      - op: remove
        path: /spec/ovn/template/ovnController

replacements:
  # configure neutron customServiceConfig
  - source:
      kind: ConfigMap
      name: service-values
      fieldPath: data.neutron.customServiceConfig
    targets:
      - select:
          kind: OpenStackControlPlane
        fieldPaths:
          - spec.neutron.template.customServiceConfig
        options:
          create: true
