#
# CHANGEME:
#
# - Change "spec.dns.template.options[0].values[0]" to match the IP of your upstream DNS server
# - Change "spec.dns.template.override.service.metadata.annotations["metallb.universe.tf/loadBalancerIPs"]"
#   to match the VIP for your ctlplane network, if necessary
# - Change "spec.storageClass" to the storage class appropriate for your OpenShift cluster
#

apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack-galera-network-isolation
  namespace: openstack
spec:
  barbican:
    apiOverride:
      route: {}
    template:
      barbicanAPI:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
        replicas: 1
      barbicanKeystoneListener:
        replicas: 1
      barbicanWorker:
        replicas: 1
      databaseInstance: openstack
      secret: osp-secret
  cinder:
    apiOverride:
      route: {}
    template:
      cinderAPI:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
      cinderBackup:
        networkAttachments:
          - storage
        replicas: 0
      cinderScheduler:
        replicas: 1
      cinderVolumes:
        volume1:
          networkAttachments:
            - storage
          replicas: 0
      databaseInstance: openstack
      secret: osp-secret
  designate:
    apiOverride:
      route: {}
    enabled: false
    template:
      databaseInstance: openstack
      designateAPI:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
      designateBackendbind9:
        networkAttachements:
          - designate
        replicas: 0
      designateCentral:
        replicas: 1
      designateMdns:
        networkAttachements:
          - designate
        replicas: 0
      designateProducer:
        replicas: 0
      designateWorker:
        networkAttachements:
          - designate
        replicas: 0
      secret: osp-secret
  dns:
    template:
      options:
        - key: server
          values:
            - 192.168.122.1
      override:
        service:
          metadata:
            annotations:
              metallb.universe.tf/address-pool: ctlplane
              metallb.universe.tf/allow-shared-ip: ctlplane
              metallb.universe.tf/loadBalancerIPs: 192.168.122.80
          spec:
            type: LoadBalancer
      replicas: 1
  galera:
    enabled: true
    templates:
      openstack:
        replicas: 1
        secret: osp-secret
        storageRequest: 500M
      openstack-cell1:
        replicas: 1
        secret: osp-secret
        storageRequest: 500M
  glance:
    apiOverride:
      route: {}
    template:
      databaseInstance: openstack
      glanceAPI:
        networkAttachments:
          - storage
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
        replicas: 1
        type: single
      secret: osp-secret
      storageClass: ""
      storageRequest: 10G
  heat:
    apiOverride:
      route: {}
    cnfAPIOverride:
      route: {}
    enabled: false
    template:
      databaseInstance: openstack
      heatAPI:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
        replicas: 1
      heatEngine:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
        replicas: 1
      secret: osp-secret
  horizon:
    apiOverride:
      route: {}
    template:
      replicas: 1
      secret: osp-secret
  ironic:
    enabled: false
    template:
      databaseInstance: openstack
      ironicAPI:
        replicas: 1
      ironicConductors:
        - replicas: 1
          storageRequest: 10G
      ironicInspector:
        replicas: 1
      ironicNeutronAgent:
        replicas: 1
      secret: osp-secret
  keystone:
    apiOverride:
      route: {}
    template:
      databaseInstance: openstack
      override:
        service:
          internal:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
      secret: osp-secret
  manila:
    apiOverride:
      route: {}
    template:
      manilaAPI:
        networkAttachments:
          - internalapi
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
        replicas: 1
      manilaScheduler:
        replicas: 1
      manilaShares:
        share1:
          networkAttachments:
            - storage
          replicas: 1
  mariadb:
    enabled: false
    templates:
      openstack:
        storageRequest: 500M
      openstack-cell1:
        storageRequest: 500M
  memcached:
    templates:
      memcached:
        replicas: 1
  neutron:
    apiOverride:
      route: {}
    template:
      databaseInstance: openstack
      networkAttachments:
        - internalapi
      override:
        service:
          internal:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
      secret: osp-secret
      customServiceConfig: |
        [ml2]
        mechanism_drivers = ovn,sriovnicswitch
        [ml2_type_vlan]
        network_vlan_ranges = sriov-phy4
  nova:
    apiOverride:
      route: {}
    template:
      apiServiceTemplate:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
      metadataServiceTemplate:
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
      secret: osp-secret
      schedulerServiceTemplate:
        customServiceConfig: |
          [filter_scheduler]
          enabled_filters = AvailabilityZoneFilter, ComputeFilter, ComputeCapabilitiesFilter, ImagePropertiesFilter, ServerGroupAntiAffinityFilter, ServerGroupAffinityFilter, PciPassthroughFilter, AggregateInstanceExtraSpecsFilter
          available_filters = nova.scheduler.filters.all_filters
  octavia:
    enabled: false
    template:
      databaseInstance: openstack
      octaviaAPI:
        replicas: 1
      secret: osp-secret
  ovn:
    template:
      ovnController:
        external-ids:
          ovn-bridge: br-int
          ovn-encap-type: geneve
          system-id: random
        networkAttachment: tenant
      ovnDBCluster:
        ovndbcluster-nb:
          dbType: NB
          networkAttachment: internalapi
          storageRequest: 10G
        ovndbcluster-sb:
          dbType: SB
          networkAttachment: internalapi
          storageRequest: 10G
      ovnNorthd:
        networkAttachment: internalapi
  placement:
    apiOverride:
      route: {}
    template:
      databaseInstance: openstack
      override:
        service:
          internal:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
      secret: osp-secret
  rabbitmq:
    templates:
      rabbitmq:
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.85
            spec:
              type: LoadBalancer
      rabbitmq-cell1:
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.86
            spec:
              type: LoadBalancer
  redis:
    enabled: false
  secret: osp-secret
  storageClass: local-storage
  swift:
    enabled: true
    proxyOverride:
      route: {}
    template:
      swiftProxy:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
        replicas: 1
      swiftRing:
        ringReplicas: 1
      swiftStorage:
        replicas: 1
  telemetry:
    enabled: true
    template:
      autoscaling:
        aodh:
          databaseInstance: openstack
          memcachedInstance: memcached
          secret: osp-secret
        enabled: false
        heatInstance: heat
        prometheus:
          deployPrometheus: false
      ceilometer:
        enabled: true
        secret: osp-secret
