#
# Change the fields below for certain node names, interfaces and IPs to match your environment.
# "spec.desiredState.interfaces" can be added to support additional networks.
#

apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  labels:
    osp/interface: enp6s0
  name: enp6s0-crc-n5gv4-master-0
spec:
  desiredState:
    dns-resolver:
      config:
        search: []
        server:
        - 192.168.122.1
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.122.1
        next-hop-interface: enp6s0
    interfaces:
    - description: internalapi vlan interface
      ipv4:
        address:
        - ip: 172.17.0.5
          prefix-length: 24
        enabled: true
        dhcp: false
      ipv6:
        enabled: false
      name: enp6s0.401
      state: up
      type: vlan
      vlan:
        base-iface: enp6s0
        id: 401
    - description: storage vlan interface
      ipv4:
        address:
        - ip: 172.18.0.5
          prefix-length: 24
        enabled: true
        dhcp: false
      ipv6:
        enabled: false
      name: enp6s0.402
      state: up
      type: vlan
      vlan:
        base-iface: enp6s0
        id: 402
    - description: tenant vlan interface
      ipv4:
        address:
        - ip: 172.19.0.5
          prefix-length: 24
        enabled: true
        dhcp: false
      ipv6:
        enabled: false
      name: enp6s0.403
      state: up
      type: vlan
      vlan:
        base-iface: enp6s0
        id: 403
    - description: Configuring enp6s0
      ipv4:
        address:
        - ip: 192.168.122.10
          prefix-length: 24
        enabled: true
        dhcp: false
      ipv6:
        enabled: false
      mtu: 1500
      name: enp6s0
      state: up
      type: ethernet
  nodeSelector:
    kubernetes.io/hostname: crc-n5gv4-master-0
    node-role.kubernetes.io/worker: ""
