apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneDeployment
metadata:
  name: openstack-edpm-ipam
  namespace: openstack
spec:
  nodeSets:
  - openstack-edpm-ipam
  # Listing the OpenStackDataPlaneServices here does work unless they
  # have been pre-created manually by the user
  servicesOverride: []
