---
apiVersion: v1
kind: ConfigMap
metadata:
  name: network-values
  annotations:
    config.kubernetes.io/local-config: "true"

data:
  openstack-operator-image: "quay.io/openstack-k8s-operators/openstack-operator-index:latest"

  node_0:
    name: master-0
    internalapi_ip: 172.17.0.10
    tenant_ip: 172.19.0.10
    ctlplane_ip: 192.168.122.10
    storage_ip: 172.18.0.10
  node_1:
    name: master-1
    internalapi_ip: 172.17.0.11
    tenant_ip: 172.19.0.11
    ctlplane_ip: 192.168.122.11
    storage_ip: 172.18.0.11
  node_2:
    name: master-2
    internalapi_ip: 172.17.0.12
    tenant_ip: 172.19.0.12
    ctlplane_ip: 192.168.122.12
    storage_ip: 172.18.0.12

  ctlplane:
    dnsDomain: ctlplane.openstack.lab
    subnets:
      - allocationRanges:
          - end: 192.168.122.120
            start: 192.168.122.100
          - end: 192.168.122.200
            start: 192.168.122.150
        cidr: 192.168.122.0/24
        gateway: 192.168.122.1
        routes:
          - destination: 192.168.123.0/24
            nexthop: 192.168.122.1
          - destination: 192.168.124.0/24
            nexthop: 192.168.122.1
        name: subnet1
      - allocationRanges:
          - end: 192.168.123.120
            start: 192.168.123.100
          - end: 192.168.123.200
            start: 192.168.123.150
        cidr: 192.168.123.0/24
        gateway: 192.168.123.1
        routes:
          - destination: 192.168.122.0/24
            nexthop: 192.168.123.1
          - destination: 192.168.124.0/24
            nexthop: 192.168.123.1
        name: subnet2
      - allocationRanges:
          - end: 192.168.124.120
            start: 192.168.124.100
          - end: 192.168.124.200
            start: 192.168.124.150
        cidr: 192.168.124.0/24
        gateway: 192.168.124.1
        routes:
          - destination: 192.168.122.0/24
            nexthop: 192.168.124.1
          - destination: 192.168.123.0/24
            nexthop: 192.168.124.1
        name: subnet3
    prefix-length: 24
    iface: enp7s0
    mtu: 1500
    lb_addresses:
      - 192.168.122.80-192.168.122.90
    endpoint_annotations:
      metallb.universe.tf/address-pool: ctlplane
      metallb.universe.tf/allow-shared-ip: ctlplane
      metallb.universe.tf/loadBalancerIPs: 192.168.122.80
    net-attach-def: |
      {
        "cniVersion": "0.3.1",
        "name": "ctlplane",
        "type": "macvlan",
        "master": "enp7s0",
        "ipam": {
          "type": "whereabouts",
          "range": "192.168.122.0/24",
          "range_start": "192.168.122.30",
          "range_end": "192.168.122.70",
          "routes": [
            {
              "dst": "192.168.123.0/24",
              "gw": "192.168.122.1"
            },
            {
              "dst": "192.168.124.0/24",
              "gw": "192.168.122.1"
            }
          ]
        }
      }

  internalapi:
    dnsDomain: internalapi.openstack.lab
    subnets:
      - allocationRanges:
          - end: 172.17.0.250
            start: 172.17.0.100
        cidr: 172.17.0.0/24
        gateway: 172.17.0.1
        routes:
          - destination: 172.17.1.0/24
            nexthop: 172.17.0.1
          - destination: 172.17.2.0/24
            nexthop: 172.17.0.1
        name: subnet1
        vlan: 20
      - allocationRanges:
          - end: 172.17.1.250
            start: 172.17.1.100
        cidr: 172.17.1.0/24
        gateway: 172.17.1.1
        routes:
          - destination: 172.17.0.0/24
            nexthop: 172.17.1.1
          - destination: 172.17.2.0/24
            nexthop: 172.17.1.1
        name: subnet2
        vlan: 30
      - allocationRanges:
          - end: 172.17.2.250
            start: 172.17.2.100
        cidr: 172.17.2.0/24
        gateway: 172.17.2.1
        routes:
          - destination: 172.17.0.0/24
            nexthop: 172.17.2.1
          - destination: 172.17.1.0/24
            nexthop: 172.17.2.1
        name: subnet3
        vlan: 40
    mtu: 1500
    prefix-length: 24
    iface: internalapi
    vlan: 20
    base_iface: enp7s0
    lb_addresses:
      - 172.17.0.80-172.17.0.90
    endpoint_annotations:
      metallb.universe.tf/address-pool: internalapi
      metallb.universe.tf/allow-shared-ip: internalapi
      metallb.universe.tf/loadBalancerIPs: 172.17.0.80
    net-attach-def: |
      {
        "cniVersion": "0.3.1",
        "name": "internalapi",
        "type": "macvlan",
        "master": "internalapi",
        "ipam": {
          "type": "whereabouts",
          "range": "172.17.0.0/24",
          "range_start": "172.17.0.30",
          "range_end": "172.17.0.70",
          "routes": [
            {
              "dst": "172.17.1.0/24",
              "gw": "172.17.0.1"
            },
            {
              "dst": "172.17.2.0/24",
              "gw": "172.17.0.1"
            }
          ]
        }
      }

  storage:
    dnsDomain: storage.openstack.lab
    subnets:
      - allocationRanges:
          - end: 172.18.0.250
            start: 172.18.0.100
        cidr: 172.18.0.0/24
        gateway: 172.18.0.1
        routes:
          - destination: 172.18.1.0/24
            nexthop: 172.18.0.1
          - destination: 172.18.2.0/24
            nexthop: 172.18.0.1
        name: subnet1
        vlan: 21
      - allocationRanges:
          - end: 172.18.1.250
            start: 172.18.1.100
        cidr: 172.18.1.0/24
        gateway: 172.18.1.1
        routes:
          - destination: 172.18.0.0/24
            nexthop: 172.18.1.1
          - destination: 172.18.2.0/24
            nexthop: 172.18.1.1
        name: subnet2
        vlan: 31
      - allocationRanges:
          - end: 172.18.2.250
            start: 172.18.2.100
        cidr: 172.18.2.0/24
        gateway: 172.18.2.1
        routes:
          - destination: 172.18.0.0/24
            nexthop: 172.18.2.1
          - destination: 172.18.1.0/24
            nexthop: 172.18.2.1
        name: subnet3
        vlan: 41
    mtu: 1500
    prefix-length: 24
    iface: storage
    vlan: 21
    base_iface: enp7s0
    lb_addresses:
      - 172.18.0.80-172.18.0.90
    net-attach-def: |
      {
        "cniVersion": "0.3.1",
        "name": "storage",
        "type": "macvlan",
        "master": "storage",
        "ipam": {
          "type": "whereabouts",
          "range": "172.18.0.0/24",
          "range_start": "172.18.0.30",
          "range_end": "172.18.0.70",
          "routes": [
            {
              "dst": "172.18.1.0/24",
              "gw": "172.18.0.1"
            },
            {
              "dst": "172.18.2.0/24",
              "gw": "172.18.0.1"
            }
          ]
        }
      }

  tenant:
    dnsDomain: tenant.openstack.lab
    subnets:
      - allocationRanges:
          - end: 172.19.0.250
            start: 172.19.0.100
        cidr: 172.19.0.0/24
        gateway: 172.19.0.1
        routes:
          - destination: 172.19.1.0/24
            nexthop: 172.19.0.1
          - destination: 172.19.2.0/24
            nexthop: 172.19.0.1
        name: subnet1
        vlan: 22
      - allocationRanges:
          - end: 172.19.1.250
            start: 172.19.1.100
        cidr: 172.19.1.0/24
        gateway: 172.19.1.1
        routes:
          - destination: 172.19.0.0/24
            nexthop: 172.19.1.1
          - destination: 172.19.2.0/24
            nexthop: 172.19.1.1
        name: subnet2
        vlan: 32
      - allocationRanges:
          - end: 172.19.2.250
            start: 172.19.2.100
        cidr: 172.19.2.0/24
        gateway: 172.19.2.1
        routes:
          - destination: 172.19.0.0/24
            nexthop: 172.19.2.1
          - destination: 172.19.1.0/24
            nexthop: 172.19.2.1
        name: subnet3
        vlan: 42
    mtu: 1500
    prefix-length: 24
    iface: tenant
    vlan: 22
    base_iface: enp7s0
    lb_addresses:
      - 172.19.0.80-172.19.0.90
    net-attach-def: |
      {
        "cniVersion": "0.3.1",
        "name": "tenant",
        "type": "macvlan",
        "master": "tenant",
        "ipam": {
          "type": "whereabouts",
          "range": "172.19.0.0/24",
          "range_start": "172.19.0.30",
          "range_end": "172.19.0.70",
          "routes": [
            {
              "dst": "172.19.1.0/24",
              "gw": "172.19.0.1"
            },
            {
              "dst": "172.19.2.0/24",
              "gw": "172.19.0.1"
            }
          ]
        }
      }



  dns-resolver:
    config:
      server:
        - 192.168.122.1
      search: []
    options:
      - key: server
        values:
          - 192.168.122.1

  routes:
    config:
      # ctlplane
      - destination: 192.168.123.0/24
        metric: 150
        next-hop-address: 192.168.122.1
        next-hop-interface: enp7s0
      - destination: 192.168.124.0/24
        metric: 150
        next-hop-address: 192.168.122.1
        next-hop-interface: enp7s0
      # internalapi
      - destination: 172.17.1.0/24
        metric: 150
        next-hop-address: 172.17.0.1
        next-hop-interface: internalapi
      - destination: 172.17.2.0/24
        metric: 150
        next-hop-address: 172.17.0.1
        next-hop-interface: internalapi
      # storage
      - destination: 172.18.1.0/24
        metric: 150
        next-hop-address: 172.18.0.1
        next-hop-interface: storage
      - destination: 172.18.2.0/24
        metric: 150
        next-hop-address: 172.18.0.1
        next-hop-interface: storage
      # tenant
      - destination: 172.19.1.0/24
        metric: 150
        next-hop-address: 172.19.0.1
        next-hop-interface: tenant
      - destination: 172.19.2.0/24
        metric: 150
        next-hop-address: 172.19.0.1
        next-hop-interface: tenant

  rabbitmq:
    endpoint_annotations:
      metallb.universe.tf/address-pool: internalapi
      metallb.universe.tf/loadBalancerIPs: 172.17.0.85
  rabbitmq-cell1:
    endpoint_annotations:
      metallb.universe.tf/address-pool: internalapi
      metallb.universe.tf/loadBalancerIPs: 172.17.0.86

  lbServiceType: LoadBalancer
  storageClass: lvms-local-storage

