apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: edpm-custom-docker-policy
spec:
  label: dataplane-deployment-custom-service
  playbookContents: |
    - hosts: all
      tasks:
        - name: Do no block on signature for container
          ansible.builtin.copy:
            content: |
              {
                  "default": [
                      {
                          "type": "insecureAcceptAnything"
                      }
                  ],
                  "transports": {
                      "docker": {
                          "registry.access.redhat.com": [
                              {
                                  "type": "insecureAcceptAnything"
                              }
                          ],
                          "registry.redhat.io": [
                              {
                                  "type": "insecureAcceptAnything"
                              }
                          ]
                      },
                      "docker-daemon": {
                          "": [
                              {
                                  "type": "insecureAcceptAnything"
                              }
                          ]
                      }
                  }
              }
            dest: "/etc/containers/policy.json"
          become: true
