# local-config: referenced, but not emitted by kustomize
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: network-values
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  # nodes
  node_0:
    name: ostest-master-0
    internalapi_ip: 172.17.10.5
    tenant_ip: 172.19.10.5
    ctlplane_ip: 192.168.133.10
    storage_ip: 172.18.10.5
  node_1:
    name: ostest-master-1
    internalapi_ip: 172.17.10.6
    tenant_ip: 172.19.10.6
    ctlplane_ip: 192.168.133.11
    storage_ip: 172.18.10.6
  node_2:
    name: ostest-master-2
    internalapi_ip: 172.17.10.7
    tenant_ip: 172.19.10.7
    ctlplane_ip: 192.168.133.12
    storage_ip: 172.18.10.7

  # networks
  ctlplane:
    dnsDomain: ctlplane2.example.com
    subnets:
      - allocationRanges:
          - end: 192.168.133.120
            start: 192.168.133.100
          - end: 192.168.133.200
            start: 192.168.133.150
        cidr: 192.168.133.0/24
        gateway: 192.168.133.1
        name: subnet1
    prefix-length: 24
    iface: enp8s0
    vlan: 30
    mtu: 1500
    lb_addresses:
      - 192.168.133.80-192.168.133.90
    endpoint_annotations:
      metallb.universe.tf/address-pool: ctlplane2
      metallb.universe.tf/allow-shared-ip: ctlplane2
      metallb.universe.tf/loadBalancerIPs: 192.168.133.80
    net-attach-def: |
      {
        "cniVersion": "0.3.1",
        "name": "ctlplane",
        "type": "macvlan",
        "master": "enp8s0",
        "ipam": {
          "type": "whereabouts",
          "range": "192.168.133.0/24",
          "range_start": "192.168.133.30",
          "range_end": "192.168.133.70"
        }
      }
  internalapi:
    dnsDomain: internalapi2.example.com
    subnets:
      - allocationRanges:
          - end: 172.17.10.250
            start: 172.17.10.100
        cidr: 172.17.10.0/24
        name: subnet1
        vlan: 30
    mtu: 1500
    prefix-length: 24
    iface: internalapi2
    vlan: 30
    base_iface: enp8s0
    lb_addresses:
      - 172.17.10.80-172.17.10.90
    endpoint_annotations:
      metallb.universe.tf/address-pool: internalapi2
      metallb.universe.tf/allow-shared-ip: internalapi2
      metallb.universe.tf/loadBalancerIPs: 172.17.10.80
    net-attach-def: |
      {
        "cniVersion": "0.3.1",
        "name": "internalapi",
        "type": "macvlan",
        "master": "internalapi2",
        "ipam": {
          "type": "whereabouts",
          "range": "172.17.10.0/24",
          "range_start": "172.17.10.30",
          "range_end": "172.17.10.70"
        }
      }
  storage:
    dnsDomain: storage2.example.com
    subnets:
      - allocationRanges:
          - end: 172.18.10.250
            start: 172.18.10.100
        cidr: 172.18.10.0/24
        name: subnet1
        vlan: 31
    mtu: 1500
    prefix-length: 24
    iface: storage2
    vlan: 31
    base_iface: enp8s0
    lb_addresses:
      - 172.18.10.80-172.18.10.90
    net-attach-def: |
      {
        "cniVersion": "0.3.1",
        "name": "storage",
        "type": "macvlan",
        "master": "storage2",
        "ipam": {
          "type": "whereabouts",
          "range": "172.18.10.0/24",
          "range_start": "172.18.10.30",
          "range_end": "172.18.10.70"
        }
      }
  tenant:
    dnsDomain: tenant2.example.com
    subnets:
      - allocationRanges:
          - end: 172.19.10.250
            start: 172.19.10.100
        cidr: 172.19.10.0/24
        name: subnet1
        vlan: 32
    mtu: 1500
    prefix-length: 24
    iface: tenant2
    vlan: 32
    base_iface: enp8s0
    lb_addresses:
      - 172.19.10.80-172.19.10.90
    net-attach-def: |
      {
        "cniVersion": "0.3.1",
        "name": "tenant",
        "type": "macvlan",
        "master": "tenant2",
        "ipam": {
          "type": "whereabouts",
          "range": "172.19.10.0/24",
          "range_start": "172.19.10.30",
          "range_end": "172.19.10.70"
        }
      }
  external:
    dnsDomain: external2.example.com
    subnets:
      - allocationRanges:
          - end: 10.10.0.250
            start: 10.10.0.100
        cidr: 10.10.0.0/24
        gateway: 10.10.0.1
        name: subnet1
    mtu: 1500


  dns-resolver:
    config:
      server:
        - 192.168.133.1
      search: []
    options:
      - key: server
        values:
          - 192.168.133.1

  routes:
    config: []

  rabbitmq:
    endpoint_annotations:
      metallb.universe.tf/address-pool: internalapi2
      metallb.universe.tf/loadBalancerIPs: 172.17.10.85
  rabbitmq-cell1:
    endpoint_annotations:
      metallb.universe.tf/address-pool: internalapi2
      metallb.universe.tf/loadBalancerIPs: 172.17.10.86

  lbServiceType: LoadBalancer
  storageClass: local-storage
