---
# Define the "cinder-volume-pure-fc-secrets" Secret that contains sensitive
# information pertaining to the pure/FC backend.
apiVersion: v1
kind: Secret
metadata:
  labels:
    service: cinder
    component: cinder-volume
  name: cinder-volume-pure-fc-secrets
type: Opaque
stringData:
  cinder-volume-pure-fc-secrets: _replaced_
