---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack2
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
    - path: metadata/name
      kind: Namespace
      create: true

components:
  - ../../../../lib/dataplane/nodeset

patches:
  - target:
      kind: Secret
      name: .*
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: openstack2
