---
name: Release Branch sync

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 * * * *'

jobs:
  call-build-workflow:
    uses: openstack-k8s-operators/openstack-k8s-operators-ci/.github/workflows/release-branch-sync.yaml@main
